// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FilterControllerMZ","status":true,"description":"FilterControllerMZ","parameters":{"decimalVariable":"true","displacementImage":"DisplacementMap","global-enable Settings":"","enabledAll-ShowInOptionMenu":"false","enabledAll-Text":"Filter Effects Enabled","enabledAll-DefaultValue":"true"}}
];
